packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Core
  "typescript": "^5.9.3"
  "ts-node": "^10.9.2"
  "nodemon": "^3.1.7"
  # Utils
  "tsdown": "^0.21.5"
  "zod": "^4.3.6"
  # Linter and Formatter
  "@typescript-eslint/eslint-plugin": "^8.18.0"
  "@typescript-eslint/parser": "^8.18.0"
  "@eslint/js": "^8.57.1"
  "eslint": "^8.57.1"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-deprecation": "^3.0.0"
  "eslint-plugin-only-warn": "^1.2.1"
  "eslint-plugin-turbo": "^2.7.1"
  "prettier": "^3.4.2"
  # Durable Execution
  "@temporalio/common": "^1.16.1"
  "@temporalio/client": "^1.16.1"
  "@temporalio/worker": "^1.16.1"
  "@temporalio/activity": "^1.16.1"
  "@temporalio/envconfig": "^1.16.1"
  "@temporalio/interceptors-opentelemetry": "^1.16.1"
  "@temporalio/workflow": "^1.16.1"
  "@temporalio/ai-sdk": "^1.16.1"
  "@temporalio/nexus": "^1.16.1"
  "@temporalio/proto": "^1.16.1"
  "@temporalio/nyc-test-coverage": "^1.16.1"