/**
 * Environment Variables Keys 🔑
 */
export const ENV_KEY_TEMPORAL_ADDRESS = 'TEMPORAL_ADDRESS';
export const ENV_KEY_TEMPORAL_NAMESPACE = 'TEMPORAL_NAMESPACE';
export const ENV_KEY_TEMPORAL_SERVER_NAME_OVERRIDE = 'TEMPORAL_SERVER_NAME_OVERRIDE';
export const ENV_KEY_TEMPORAL_SERVER_ROOT_CA_CERT_PATH = 'TEMPORAL_SERVER_ROOT_CA_CERT_PATH';
export const ENV_KEY_TEMPORAL_CLIENT_CERT_PATH = 'TEMPORAL_CLIENT_CERT_PATH';
export const ENV_KEY_TEMPORAL_CLIENT_KEY_PATH = 'TEMPORAL_CLIENT_KEY_PATH';
export const ENV_KEY_TEMPORAL_CLIENT_API_KEY = 'TEMPORAL_CLIENT_API_KEY';
export const ENV_KEY_TEMPORAL_BASE_URL = 'TEMPORAL_BASE_URL';

/**
 * Default Values for Temporal Local Machine
 */
export const LOCAL_HOST_TEMPORAL_ADDRESS = 'localhost:7233';
export const DEFAULT_TEMPORAL_NAMESPACE = 'default';

/**
 * Task Queues
 */
export const GENERAL_TASK_QUEUE = 'boilerplate';